[package]
name = "rpccaps_derive"
version = "0.1.0"
authors = ["bkfox <thomas bkfox net>"]
edition = "2018"
description = "Derive macros for rpccaps"

[lib]
proc-macro = true

[dependencies]
syn = { version="1.0", features=["full"] }
quote = "1.0.3"
proc-macro2 = "1.0.10"

